version: '3.7'

services:
  api-gateway:
    restart: "always"
    environment:
      - ASPNETCORE_ENVIRONMENT="production"
      - ASPNETCORE_URLS=http://*:5001
    volumes:
      - /docker/storage/storage-gateway/appsettings.json:/app/appsettings.json
    ports:
      - 5100:5001

  webapp:
    restart: "always"
    environment:
      - ASPNETCORE_ENVIRONMENT="production"
      - ASPNETCORE_URLS=http://*:5001
    ports:
      - 5200:5001

  aggregator:
    restart: "always"
    environment:
      - ASPNETCORE_ENVIRONMENT="production"
      - ASPNETCORE_URLS=http://*:5001
    volumes:
      - /docker/storage/storage-aggregator/appsettings.json:/app/appsettings.json
    ports:
      - 5102:5001

  api-dataprotection:
    restart: "always"
    environment:
      - ASPNETCORE_ENVIRONMENT="production"
      - ASPNETCORE_URLS=http://*:5001
    volumes:
      - /docker/storage/storage-data-protection/appsettings.json:/app/appsettings.json
    # ports:
    #   - 5101:5001

  proxy-dataprotection:
    restart: "always"
    environment:
      - ASPNETCORE_ENVIRONMENT="production"
      - ASPNETCORE_URLS=http://*:5001
    volumes:
      - /docker/storage/proxy-data-protection/appsettings.json:/app/appsettings.json
    # ports:
    #   - 5201:5001

  api-utility:
    restart: "always"
    environment:
      - ASPNETCORE_ENVIRONMENT="production"
      - ASPNETCORE_URLS=http://*:5001
    volumes:
      - /docker/storage/storage-utility/appsettings.json:/app/appsettings.json
    # ports:
    #   - 5103:5001

  proxy-utility:
    restart: "always"
    environment:
      - ASPNETCORE_ENVIRONMENT="production"
      - ASPNETCORE_URLS=http://*:5001
    volumes:
      - /docker/storage/proxy-utility/appsettings.json:/app/appsettings.json
    # ports:
    #   - 5203:5001

  api-prodotti:
    restart: "always"
    environment:
      - ASPNETCORE_ENVIRONMENT="production"
      - ASPNETCORE_URLS=http://*:5001
    volumes:
      - /docker/storage/storage-prodotti/appsettings.json:/app/appsettings.json
    # ports:
    #   - 5104:5001

  proxy-prodotti:
    restart: "always"
    environment:
      - ASPNETCORE_ENVIRONMENT="production"
      - ASPNETCORE_URLS=http://*:5001
    volumes:
      - /docker/storage/proxy-prodotti/appsettings.json:/app/appsettings.json
    # ports:
    #   - 5204:5001