version: '3.7'

services:
  api-gateway:
    restart: "always"
    environment:
      - ASPNETCORE_ENVIRONMENT="production"
      - ASPNETCORE_URLS=http://*:5001
    volumes:
      - /docker/storage/storage-gateway/appsettings.json:/app/appsettings.json
    ports:
      - 5100:5001

  webapp:
    restart: "always"
    environment:
      - ASPNETCORE_ENVIRONMENT="production"
      - ASPNETCORE_URLS=http://*:80
    volumes:
      - /docker/storage/storage-webapp/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 5200:80

  aggregator:
    restart: "always"
    environment:
      - ASPNETCORE_ENVIRONMENT="production"
      - ASPNETCORE_URLS=http://*:5001
    volumes:
      - /docker/storage/storage-aggregator/appsettings.json:/app/appsettings.json
    ports:
      - 5102:5001

  api-dataprotection:
    restart: "always"
    environment:
      - ASPNETCORE_ENVIRONMENT="production"
      - ASPNETCORE_URLS=http://*:5001
    volumes:
      - /docker/storage/storage-data-protection/appsettings.json:/app/appsettings.json

  proxy-dataprotection:
    restart: "always"
    environment:
      - ASPNETCORE_ENVIRONMENT="production"
      - ASPNETCORE_URLS=http://*:5001
    volumes:
      - /docker/storage/proxy-data-protection/appsettings.json:/app/appsettings.json

  api-utility:
    restart: "always"
    environment:
      - ASPNETCORE_ENVIRONMENT="production"
      - ASPNETCORE_URLS=http://*:5001
    volumes:
      - /docker/storage/storage-utility/appsettings.json:/app/appsettings.json

  proxy-utility:
    restart: "always"
    environment:
      - ASPNETCORE_ENVIRONMENT="production"
      - ASPNETCORE_URLS=http://*:5001
    volumes:
      - /docker/storage/proxy-utility/appsettings.json:/app/appsettings.json

  api-prodotti:
    restart: "always"
    environment:
      - ASPNETCORE_ENVIRONMENT="production"
      - ASPNETCORE_URLS=http://*:5001
    volumes:
      - /docker/storage/storage-prodotti/appsettings.json:/app/appsettings.json

  proxy-prodotti:
    restart: "always"
    environment:
      - ASPNETCORE_ENVIRONMENT="production"
      - ASPNETCORE_URLS=http://*:5001
    volumes:
      - /docker/storage/proxy-prodotti/appsettings.json:/app/appsettings.json

  api-categorie:
    restart: "always"
    environment:
      - ASPNETCORE_ENVIRONMENT="production"
      - ASPNETCORE_URLS=http://*:5001
    volumes:
      - /docker/storage/storage-categorie/appsettings.json:/app/appsettings.json

  proxy-categorie:
    restart: "always"
    environment:
      - ASPNETCORE_ENVIRONMENT="production"
      - ASPNETCORE_URLS=http://*:5001
    volumes:
      - /docker/storage/proxy-categorie/appsettings.json:/app/appsettings.json

  api-operazioniavvio:
    restart: "always"
    environment:
      - ASPNETCORE_ENVIRONMENT="production"
      - ASPNETCORE_URLS=http://*:5001
    volumes:
      - /docker/storage/storage-operazioniavvio/appsettings.json:/app/appsettings.json

  proxy-operazioniavvio:
    restart: "always"
    environment:
      - ASPNETCORE_ENVIRONMENT="production"
      - ASPNETCORE_URLS=http://*:5001
    volumes:
      - /docker/storage/proxy-operazioniavvio/appsettings.json:/app/appsettings.json