// <auto-generated />
using System;
using GestioneSagre.Prodotti.DataAccessLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestioneSagre.Prodotti.DataAccessLayer.Migrations
{
    [DbContext(typeof(ProdottiDbContext))]
    [Migration("20230921095423_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestioneSagre.Prodotti.DataAccessLayer.Entities.Prodotto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AvvisoScorta")
                        .HasColumnType("bit");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("IdCategoria")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdFesta")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Prenotazione")
                        .HasColumnType("bit");

                    b.Property<bool>("ProdottoAttivo")
                        .HasColumnType("bit");

                    b.Property<int>("Quantita")
                        .HasColumnType("int");

                    b.Property<bool>("QuantitaAttiva")
                        .HasColumnType("bit");

                    b.Property<int>("QuantitaScorta")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Prodotti", (string)null);
                });

            modelBuilder.Entity("GestioneSagre.Prodotti.DataAccessLayer.Entities.Prodotto", b =>
                {
                    b.OwnsOne("GestioneSagre.Prodotti.Shared.Models.ValueObjects.Price", "Prezzo", b1 =>
                        {
                            b1.Property<Guid>("ProdottoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<string>("Currency")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ProdottoId");

                            b1.ToTable("Prodotti");

                            b1.WithOwner()
                                .HasForeignKey("ProdottoId");
                        });

                    b.Navigation("Prezzo");
                });
#pragma warning restore 612, 618
        }
    }
}
