// <auto-generated />
using System;
using GestioneSagre.OperazioniAvvio.DataAccessLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestioneSagre.OperazioniAvvio.DataAccessLayer.Migrations
{
    [DbContext(typeof(OperazioniAvvioDbContext))]
    [Migration("20231114133502_RemoveTableRelationships")]
    partial class RemoveTableRelationships
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestioneSagre.OperazioniAvvio.DataAccessLayer.Entities.Festa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataFine")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInizio")
                        .HasColumnType("datetime2");

                    b.Property<string>("StatusFesta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Feste", (string)null);
                });

            modelBuilder.Entity("GestioneSagre.OperazioniAvvio.DataAccessLayer.Entities.Impostazione", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("GestioneCategorie")
                        .HasColumnType("bit");

                    b.Property<bool>("GestioneMenu")
                        .HasColumnType("bit");

                    b.Property<Guid>("IdFesta")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("StampaCarta")
                        .HasColumnType("bit");

                    b.Property<bool>("StampaRicevuta")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Impostazioni", (string)null);
                });

            modelBuilder.Entity("GestioneSagre.OperazioniAvvio.DataAccessLayer.Entities.Intestazione", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Edizione")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("IdFesta")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Luogo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Titolo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Intestazioni", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
