// <auto-generated />
using System;
using GestioneSagre.Utility.DataAccessLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestioneSagre.Utility.DataAccessLayer.Migrations
{
    [DbContext(typeof(UtilityDbContext))]
    [Migration("20230914133921_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestioneSagre.Utility.DataAccessLayer.Entities.ClienteTipo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Valore")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("TipoCliente", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("69ad8e35-b445-42a4-b3c2-8c3fb0a27750"),
                            Valore = "CLIENTE"
                        },
                        new
                        {
                            Id = new Guid("0c86400f-4dee-4354-99b2-f680cc6e8a74"),
                            Valore = "STAFF"
                        });
                });

            modelBuilder.Entity("GestioneSagre.Utility.DataAccessLayer.Entities.PagamentoTipo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Valore")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("TipoPagamento", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("6340fa14-271f-4565-ace2-3249e5f474ef"),
                            Valore = "CONTANTI"
                        });
                });

            modelBuilder.Entity("GestioneSagre.Utility.DataAccessLayer.Entities.ScontrinoStato", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Valore")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("StatoScontrino", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("bec5963a-9a76-4610-a951-2e3e9e66fd82"),
                            Valore = "APERTO"
                        },
                        new
                        {
                            Id = new Guid("dced34e3-0be1-4b04-9895-4816e9642644"),
                            Valore = "IN ELABORAZIONE"
                        },
                        new
                        {
                            Id = new Guid("5ac9505a-726a-4106-89f8-a86639558d2d"),
                            Valore = "DA INCASSARE"
                        },
                        new
                        {
                            Id = new Guid("80087fd8-09bb-45a5-a4b7-afb6007ed592"),
                            Valore = "PAGATO"
                        },
                        new
                        {
                            Id = new Guid("828e7daa-f1cb-45eb-981a-983fe5cad00b"),
                            Valore = "CHIUSO"
                        },
                        new
                        {
                            Id = new Guid("0a4bfb8a-7e75-46fe-a8c1-8d1eb3011686"),
                            Valore = "ANNULLATO"
                        });
                });

            modelBuilder.Entity("GestioneSagre.Utility.DataAccessLayer.Entities.ScontrinoTipo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Valore")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("TipoScontrino", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("6e00a736-d5b4-4494-aa89-c2caa726d4e3"),
                            Valore = "PAGAMENTO"
                        },
                        new
                        {
                            Id = new Guid("4981bcd3-6860-4545-8786-832abdbbe60d"),
                            Valore = "OMAGGIO"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
