global using System.Net.Mime;
global using GestioneSagre.DataProtection.BusinessLayer.Commands;
global using GestioneSagre.DataProtection.BusinessLayer.Extensions;
global using GestioneSagre.DataProtection.Controllers.Common;
global using GestioneSagre.DataProtection.Shared.Models.InputModels;
global using GestioneSagre.DataProtection.Shared.Models.ViewModels;
global using GestioneSagre.GenericServices.Extensions;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.AspNetCore.Server.Kestrel.Core;
