FROM mcr.microsoft.com/mssql/server:2022-CU5-ubuntu-20.04

#ENV DEBIAN_FRONTEND=noninteractive
#RUN apt-get update
#RUN apt-get -y install tzdata
#RUN ln -fs /usr/share/zoneinfo/Europe/Rome /etc/localtime 
#RUN dpkg-reconfigure --frontend noninteractive tzdata