name: Deploy to VPS Aruba
on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  deploy_server:
    name: Deploy VPS Aruba
    runs-on: ubuntu-latest
    steps:
      - name: Create a file
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
                    cd /docker/gestionesagre
                    bash docker-compose down
                    bash docker-compose up -d
