name: Push to DockerHub

on:
  # push:
  #   branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Push images to DockerHub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0

      - name: Login to Docker Hub
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.2.0

      - name: Build and push Gateway
        uses: docker/build-push-action@v5.3.0
        with:
         context: .
         file: ./src/Gateway/GestioneSagre.Gateway/Dockerfile
         push: true
         tags: ${{ secrets.DOCKER_USERNAME }}/gsweb-gateway:latest

      - name: Build and push Data Protection
        uses: docker/build-push-action@v5.3.0
        with:
         context: .
         file: ./src/DataProtection/GestioneSagre.DataProtection/Dockerfile
         push: true
         tags: ${{ secrets.DOCKER_USERNAME }}/gsweb-dataprotection:latest
         
      - name: Build and push Aggregator
        uses: docker/build-push-action@v5.3.0
        with:
         context: .
         file: ./src/Aggregator/GestioneSagre.Aggregator/Dockerfile
         push: true
         tags: ${{ secrets.DOCKER_USERNAME }}/gsweb-aggregator:latest

      - name: Build and push Reverse Proxy
        uses: docker/build-push-action@v5.3.0
        with:
         context: .
         file: ./src/ReverseProxy/GestioneSagre.ReverseProxy/Dockerfile
         push: true
         tags: ${{ secrets.DOCKER_USERNAME }}/gsweb-reverseproxy:latest

      - name: Build and push Prodotti
        uses: docker/build-push-action@v5.3.0
        with:
         context: .
         file: ./src/Prodotti/GestioneSagre.Prodotti/Dockerfile
         push: true
         tags: ${{ secrets.DOCKER_USERNAME }}/gsweb-prodotti:latest

      - name: Build and push Categorie
        uses: docker/build-push-action@v5.3.0
        with:
         context: .
         file: ./src/Categorie/GestioneSagre.Categorie/Dockerfile
         push: true
         tags: ${{ secrets.DOCKER_USERNAME }}/gsweb-categorie:latest

      - name: Build and push Utility
        uses: docker/build-push-action@v5.3.0
        with:
         context: .
         file: ./src/Utility/GestioneSagre.Utility/Dockerfile
         push: true
         tags: ${{ secrets.DOCKER_USERNAME }}/gsweb-utility:latest

      - name: Build and push Operazioni Avvio
        uses: docker/build-push-action@v5.3.0
        with:
         context: .
         file: ./src/OperazioniAvvio/GestioneSagre.OperazioniAvvio/Dockerfile
         push: true
         tags: ${{ secrets.DOCKER_USERNAME }}/gsweb-operazioniavvio:latest

      - name: Regenerate environments on Aruba
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
                    bash /docker/gestionesagre/rigeneraAmbiente.sh
