name: Push to DockerHub

on:
  push:
    branches: [ "main" ]
    #paths:
    #  - '/src/**/**/**'
    #  - '/src/**/GestioneSagre.*/**'
  workflow_dispatch:

jobs:
  build:
    name: Push images to DockerHub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Gateway
        uses: docker/build-push-action@v4
        with:
         context: .
         file: ./src/Gateway/GestioneSagre.Gateway/Dockerfile
         push: true
         tags: ${{ secrets.DOCKER_USERNAME }}/gsweb-gateway:latest

      - name: Build and push Data Protection
        uses: docker/build-push-action@v4
        with:
         context: .
         file: ./src/DataProtection/GestioneSagre.DataProtection/Dockerfile
         push: true
         tags: ${{ secrets.DOCKER_USERNAME }}/gsweb-dataprotection:latest
         
      - name: Build and push Aggregator
        uses: docker/build-push-action@v4
        with:
         context: .
         file: ./src/Aggregator/GestioneSagre.Aggregator/Dockerfile
         push: true
         tags: ${{ secrets.DOCKER_USERNAME }}/gsweb-aggregator:latest

      - name: Build and push Reverse Proxy
        uses: docker/build-push-action@v4
        with:
         context: .
         file: ./src/ReverseProxy/GestioneSagre.ReverseProxy/Dockerfile
         push: true
         tags: ${{ secrets.DOCKER_USERNAME }}/gsweb-reverseproxy:latest

      - name: Regenerate environments on Aruba
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
                    bash /docker/gestionesagre/rigeneraAmbiente.sh
