on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push Gateway
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./src/GestioneSagre.Gateway/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/gsweb-gateway:latest
      -
        name: Build and push Redis
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/redis/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/gsweb-redis:latest
