name: .NET Build and Test

on:
  #push:
  #  branches: [ "main" ]
  #pull_request:   
  #  branches: [ main, develop ]
  workflow_dispatch:

env:
  NET_VERSION: "6.0.x"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      #uses: actions/checkout@v3
      uses: actions/checkout@v4.1.0
      # with:
        # fetch-depth: 0
    
    - name: Setup .NET SDK ${{ env.NET_VERSION }}
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.NET_VERSION }}
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage

    - name: Code Coverage Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: coverage/**/coverage.cobertura.xml
        badge: true
        fail_below_min: true
        format: markdown
        hide_branch_rate: false
        hide_complexity: true
        indicators: true
        output: both
        thresholds: '60 90'

    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      #if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: code-coverage-results.md

    - name: Write Coverage to Job Summary
      run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY
